# .github/workflows/django-ci.yml
name: Django CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:15
        env:
          POSTGRES_DB: heroku_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: imrandell
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      POSTGRES_DB: heroku_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: imrandell
      POSTGRES_HOST: 127.0.0.1
      POSTGRES_PORT: 5432
      SECRET_KEY: 3%-y(g)*57!)&!00!a7$&47k!&_2=3jw$@db#5%bhba-b_cn_@
      DEBUG: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Wait for DB to be ready
        run: |
          until pg_isready -h 127.0.0.1 -p 5432 -U postgres; do
            echo "Waiting for PostgreSQL..."
            sleep 2
          done

      - name: Run migrations
        run: python manage.py migrate

      - name: Run tests
        run: python manage.py test
