pipeline {
    agent any

    environment {
        VENV = 'heroku_env' // Fixed syntax: `=` instead of `:`
    }

    stages {
        stage('Checkout Code') {
            steps {
                git branch: 'main', url: 'https://github.com/imranworkspace/dj_herokuPro.git' // Fixed keyword spacing
            }
        }

        stage('Set up virtual environment') {
            steps {
                bat "python -m venv %VENV%"
                bat "%VENV%\\Scripts\\python -m pip install --upgrade pip"
                bat "%VENV%\\Scripts\\pip install -r requirements.txt"
            }
        }

        stage('Run the tests') {
            steps {
                bat "%VENV%\\Scripts\\python manage.py test"
            }
        }
    }
}
